name: Run Linear Regression

on:
  push:
    branches: [ "main" ]
    paths:
      - 'data.csv'
      - 'regression.py'

jobs:
  run-regression:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run regression
      run: python regression.py

    - name: Upload regression results
      uses: actions/upload-artifact@v4
      with:
        name: regression-results
        path: regression_output.txt
